---
- name: Check if {{ xcode_app_output_path }} already exists
  stat:
    path: "{{ xcode_app_output_path }}"
  register: xcode_installed

- name: Remove existing Xcode.app
  file:
    path: "/Applications/Xcode.app"
    state: absent
  become: true
  
- name: Remove existing Xcode-beta.app
  file:
    path: "/Applications/Xcode-beta.app"
    state: absent
  become: true

- name: Check if {{ xcode_xip_name }} is ready for extraction
  stat:
    path: "/Applications/{{ xcode_xip_name }}"
  register: xip_installer

- name: Copy {{ xcode_xip_name }} to target machine (from playbooks/files/ if relative)
  copy:
    src: "{{ xcode_xip_path }}"
    dest: "/Applications/{{ xcode_xip_name }}"
  when:
    - not xcode_installed.stat.exists
    - not xip_installer.stat.exists

- name: Extract {{ xcode_xip_name }}
  command: xip -x {{ xcode_xip_name }}
  args:
    chdir: "/Applications"
  when:
    - not xcode_installed.stat.exists

- name: Check if xcode.app is created
  stat:
    path: "/Applications/Xcode.app"
  register: xcode_app_created

- name: Check if xcode-beta.app is created
  stat:
    path: "/Applications/Xcode-beta.app"
  register: xcode_beta_app_created

- name: Move Xcode.app to {{ xcode_app_output_path }}
  command: mv Xcode.app {{ xcode_app_output_path }}
  args:
    chdir: "/Applications"
    creates: "{{ xcode_app_output_path }}"
  when:
    - not xcode_installed.stat.exists
    - xcode_app_created.stat.exists

- name: Move Xcode-beta.app to {{ xcode_app_output_path }}
  command: mv Xcode-beta.app {{ xcode_app_output_path }}
  args:
    chdir: "/Applications"
    creates: "{{ xcode_app_output_path }}"
  when:
    - not xcode_installed.stat.exists
    - xcode_beta_app_created.stat.exists
    
- name: Validate xcode
  command: "{{ xcode_app_output_path }}/Contents/Developer/usr/bin/xcodebuild -runFirstLaunch"
  become: true

- name: Accept license (optional)
  shell: "{{ xcode_app_output_path }}/Contents/Developer/usr/bin/xcodebuild -license accept"
  become: true

- name: Remove installer {{ xcode_xip_path }}
  file:
    path: "/Applications/{{ xcode_xip_name }}"
    state: absent